import { MenuItem, MenuCategoryInfo } from "@/types";

export const MENU_CATEGORIES: MenuCategoryInfo[] = [
  { id: "coffee", label: "Coffee", labelKo: "커피" },
  { id: "beverage", label: "Beverage", labelKo: "음료" },
  { id: "blended", label: "Blended", labelKo: "블렌디드" },
  { id: "bottle", label: "Bottle", labelKo: "보틀" },
  { id: "bakery", label: "Bakery", labelKo: "베이커리" },
  { id: "ice-cream", label: "Ice-cream", labelKo: "아이스크림" },
  { id: "md", label: "MD", labelKo: "MD 상품" },
];

export const MENU_ITEMS: MenuItem[] = [
  // Coffee
  {
    id: "shaak-latte",
    name: "Shaak Latte",
    nameKo: "샥라떼",
    category: "coffee",
    image: "/images/menu/shaak-latte.jpg",
    nutrition: { calories: 150.3, sodium: 78.2, sugar: 14.1, saturatedFat: 5.6, protein: 4.6, caffeine: 85.1, allergens: "우유/대두" },
  },
  {
    id: "peanut-latte",
    name: "Peanut Latte",
    nameKo: "피넛라떼",
    category: "coffee",
    image: "/images/menu/peanut-latte.jpg",
    nutrition: { calories: 233.7, sodium: 105.2, sugar: 14.3, saturatedFat: 6.4, protein: 6.4, caffeine: 112.8, allergens: "우유/대두/밀" },
  },
  {
    id: "night-americano",
    name: "Night Americano",
    nameKo: "나이트 아메리카노",
    category: "coffee",
    image: "/images/menu/americano.jpg",
    nutrition: { calories: 12.0, sodium: 15.0, sugar: 0.0, saturatedFat: 0.0, protein: 1.0, caffeine: 216.6, allergens: null },
  },
  {
    id: "colombian-fruity-americano",
    name: "Colombian Fruity Americano",
    nameKo: "콜롬비안 프루티 아메리카노",
    category: "coffee",
    image: "/images/menu/americano.jpg",
    nutrition: null,
  },
  {
    id: "decaf-americano",
    name: "Decaf Americano",
    nameKo: "디카페인 아메리카노",
    category: "coffee",
    image: "/images/menu/americano.jpg",
    nutrition: { calories: 12.0, sodium: 5.0, sugar: 0.0, saturatedFat: 0.0, protein: 0.0, caffeine: 18.0, allergens: null },
  },
  {
    id: "cafe-latte",
    name: "Cafe Latte",
    nameKo: "카페 라떼",
    category: "coffee",
    image: "/images/menu/cafe-latte.jpg",
    nutrition: { calories: 143.0, sodium: 116.3, sugar: 10.7, saturatedFat: 5.3, protein: 8.0, caffeine: 99.6, allergens: "우유" },
  },
  {
    id: "vanilla-bean-latte",
    name: "Vanilla Bean Latte",
    nameKo: "바닐라 빈 라떼",
    category: "coffee",
    image: "/images/menu/vanilla-bean-latte.jpg",
    nutrition: { calories: 198.9, sodium: 103.9, sugar: 28.0, saturatedFat: 4.4, protein: 7.1, caffeine: 102.7, allergens: "우유" },
  },
  {
    id: "dolce-latte",
    name: "Dolce Latte",
    nameKo: "돌체 라떼",
    category: "coffee",
    image: "/images/menu/dolce-latte.jpg",
    nutrition: { calories: 252.2, sodium: 151.8, sugar: 30.7, saturatedFat: 5.8, protein: 8.0, caffeine: 110.4, allergens: "우유/대두" },
  },
  {
    id: "dolce-cold-brew-latte",
    name: "Dolce Cold Brew Latte",
    nameKo: "돌체 콜드브루 라떼",
    category: "coffee",
    image: "/images/menu/dolce-cold-brew-latte.jpg",
    nutrition: { calories: 183.5, sodium: 69.5, sugar: 22.0, saturatedFat: 3.6, protein: 3.9, caffeine: 134.1, allergens: "우유/대두" },
  },
  {
    id: "banana-cold-brew-oat-latte",
    name: "Banana Cold Brew Oat Latte",
    nameKo: "바나나 콜드브루 오트라떼",
    category: "coffee",
    image: "/images/menu/banana-cold-brew-oat-latte.jpg",
    nutrition: { calories: 203.3, sodium: 94.6, sugar: 23.7, saturatedFat: 0.0, protein: 0.0, caffeine: 86.6, allergens: null },
  },
  {
    id: "cinnamon-cafe-latte",
    name: "Cinnamon Cafe Latte",
    nameKo: "시나몬 카페 라떼",
    category: "coffee",
    image: "/images/menu/cinnamon-cafe-latte.jpg",
    nutrition: { calories: 197.1, sodium: 76.4, sugar: 27.5, saturatedFat: 2.2, protein: 6.2, caffeine: 136.3, allergens: "우유" },
  },
  {
    id: "ah-shot-chu",
    name: "Ah Shot Chu",
    nameKo: "아샷추",
    category: "coffee",
    image: "/images/menu/ah-shot-chu.jpg",
    nutrition: { calories: 172.3, sodium: 12.4, sugar: 38.2, saturatedFat: 0.0, protein: 0.4, caffeine: 113.2, allergens: "복숭아/아황산류" },
  },
  {
    id: "zero-vanilla-latte",
    name: "Zero Vanilla Latte",
    nameKo: "제로 바닐라 라떼",
    category: "coffee",
    image: "/images/menu/zero-vanilla-latte.jpg",
    nutrition: { calories: 201.6, sodium: 74.2, sugar: 10.7, saturatedFat: 3.6, protein: 5.8, caffeine: 199.8, allergens: "우유" },
  },
  {
    id: "jeju-matcha-cafe-latte",
    name: "Jeju Matcha Cafe Latte",
    nameKo: "제주 말차 카페 라떼",
    category: "coffee",
    image: "/images/menu/jeju-matcha-cafe-latte.jpg",
    nutrition: { calories: 348.9, sodium: 127.9, sugar: 32.9, saturatedFat: 8.4, protein: 13.3, caffeine: 383.6, allergens: "우유/대두" },
  },
  {
    id: "caramel-macchiato",
    name: "Caramel Macchiato",
    nameKo: "카라멜 마끼야또",
    category: "coffee",
    image: "/images/menu/caramel-macchiato.jpg",
    nutrition: { calories: 242.0, sodium: 113.7, sugar: 17.8, saturatedFat: 4.9, protein: 7.1, caffeine: 91.8, allergens: "우유/대두" },
  },
  {
    id: "cafe-mocha",
    name: "Cafe Mocha",
    nameKo: "카페 모카",
    category: "coffee",
    image: "/images/menu/cafe-mocha.jpg",
    nutrition: { calories: 247.7, sodium: 117.3, sugar: 29.9, saturatedFat: 3.6, protein: 7.2, caffeine: 222.0, allergens: "우유/대두" },
  },
  {
    id: "cold-brew-latte",
    name: "Cold Brew Latte",
    nameKo: "콜드브루 라떼",
    category: "coffee",
    image: "/images/menu/cold-brew-latte.jpg",
    nutrition: { calories: 98.8, sodium: 74.2, sugar: 7.2, saturatedFat: 3.9, protein: 4.5, caffeine: 142.8, allergens: "우유" },
  },
  {
    id: "cold-brew-americano",
    name: "Cold Brew Americano",
    nameKo: "콜드브루 아메리카노",
    category: "coffee",
    image: "/images/menu/cold-brew-americano.jpg",
    nutrition: { calories: 5.7, sodium: 2.4, sugar: 0.0, saturatedFat: 0.0, protein: 0.2, caffeine: 142.5, allergens: null },
  },
  {
    id: "espresso",
    name: "Espresso",
    nameKo: "에스프레소",
    category: "coffee",
    image: "/images/menu/espresso.jpg",
    nutrition: { calories: 2.5, sodium: 6.1, sugar: 0.0, saturatedFat: 0.0, protein: 0.2, caffeine: 124.0, allergens: null },
  },
  {
    id: "cafe-pieno",
    name: "Cafe Pieno",
    nameKo: "카페 피에노",
    category: "coffee",
    image: "/images/menu/cafe-pieno.jpg",
    nutrition: { calories: 164.3, sodium: 28.2, sugar: 9.9, saturatedFat: 7.3, protein: 1.5, caffeine: 137.8, allergens: "우유/대두" },
  },
  {
    id: "cafe-citrus",
    name: "Cafe Citrus",
    nameKo: "카페 시트러스",
    category: "coffee",
    image: "/images/menu/cafe-citrus.jpg",
    nutrition: { calories: 100.8, sodium: 29.4, sugar: 19.0, saturatedFat: 0.1, protein: 1.3, caffeine: 125.8, allergens: null },
  },
  // Beverage
  {
    id: "golden-yuzu-beauty-elixir",
    name: "Golden Yuzu Beauty Elixir",
    nameKo: "골든유자 뷰티 엘릭서",
    category: "beverage",
    image: "/images/menu/golden-yuzu-beauty-elixir.jpg",
    nutrition: { calories: 180.9, sodium: 12.9, sugar: 34.5, saturatedFat: 0.0, protein: 0.1, caffeine: null, allergens: null },
  },
  {
    id: "honey-grapefruit-tea",
    name: "Honey Grapefruit Tea",
    nameKo: "꿀 자몽 티",
    category: "beverage",
    image: "/images/menu/honey-grapefruit-tea.jpg",
    nutrition: { calories: 186.0, sodium: 11.1, sugar: 42.6, saturatedFat: 0.0, protein: 0.4, caffeine: null, allergens: null },
  },
  {
    id: "double-choco-latte",
    name: "Double Choco Latte",
    nameKo: "더블 초코라떼",
    category: "beverage",
    image: "/images/menu/double-choco-latte.jpg",
    nutrition: { calories: 294.4, sodium: 145.6, sugar: 33.3, saturatedFat: 2.7, protein: 8.0, caffeine: 6.7, allergens: "우유/대두" },
  },
  {
    id: "double-choco-bubble-tea",
    name: "Double Choco Bubble Tea",
    nameKo: "더블 초코 버블티",
    category: "beverage",
    image: "/images/menu/double-choco-bubble-tea.jpg",
    nutrition: { calories: 296.6, sodium: 120.8, sugar: 31.1, saturatedFat: 5.3, protein: 7.1, caffeine: 5.8, allergens: "우유/대두" },
  },
  {
    id: "strawberry-iced-tea",
    name: "Strawberry Iced Tea",
    nameKo: "딸기 아이스 티",
    category: "beverage",
    image: "/images/menu/strawberry-iced-tea.jpg",
    nutrition: { calories: 102.6, sodium: 6.7, sugar: 22.6, saturatedFat: 0.0, protein: 0.0, caffeine: null, allergens: null },
  },
  {
    id: "lemon-earl-grey-tea",
    name: "Lemon Earl Grey Tea",
    nameKo: "레몬 얼그레이 티",
    category: "beverage",
    image: "/images/menu/lemon-earl-grey-tea.jpg",
    nutrition: { calories: 135.0, sodium: 5.8, sugar: 5.5, saturatedFat: 0.0, protein: 30.0, caffeine: 30.9, allergens: null },
  },
  {
    id: "lemon-ade",
    name: "Lemon Ade",
    nameKo: "레몬 에이드",
    category: "beverage",
    image: "/images/menu/lemon-ade.jpg",
    nutrition: { calories: 113.7, sodium: 11.5, sugar: 26.6, saturatedFat: 0.0, protein: 0.0, caffeine: null, allergens: null },
  },
  {
    id: "lemon-yuzu-tea",
    name: "Lemon Yuzu Tea",
    nameKo: "레몬 유자 티",
    category: "beverage",
    image: "/images/menu/lemon-yuzu-tea.jpg",
    nutrition: { calories: 222.4, sodium: 48.8, sugar: 51.9, saturatedFat: 0.0, protein: 0.0, caffeine: null, allergens: null },
  },
  {
    id: "royal-milk-tea",
    name: "Royal Milk Tea",
    nameKo: "로얄 밀크 티",
    category: "beverage",
    image: "/images/menu/royal-milk-tea.jpg",
    nutrition: { calories: 212.7, sodium: 97.7, sugar: 29.8, saturatedFat: 1.8, protein: 5.8, caffeine: 18.9, allergens: "우유" },
  },
  {
    id: "real-chocolat",
    name: "Real Chocolat",
    nameKo: "리얼 쇼콜라",
    category: "beverage",
    image: "/images/menu/real-chocolat.jpg",
    nutrition: { calories: 460.9, sodium: 140.3, sugar: 50.2, saturatedFat: 4.0, protein: 10.2, caffeine: 13.5, allergens: "우유/대두" },
  },
  {
    id: "mango-latte",
    name: "Mango Latte",
    nameKo: "망고 라떼",
    category: "beverage",
    image: "/images/menu/mango-latte.jpg",
    nutrition: { calories: 239.8, sodium: 89.2, sugar: 40.0, saturatedFat: 4.0, protein: 5.3, caffeine: null, allergens: "우유/복숭아" },
  },
  {
    id: "banana-bubble-tea",
    name: "Banana Bubble Tea",
    nameKo: "바나나 버블티",
    category: "beverage",
    image: "/images/menu/banana-bubble-tea.jpg",
    nutrition: { calories: 234.9, sodium: 76.4, sugar: 33.3, saturatedFat: 3.6, protein: 5.3, caffeine: null, allergens: null },
  },
  {
    id: "white-peach-oolong",
    name: "White Peach Oolong",
    nameKo: "백도 우롱",
    category: "beverage",
    image: "/images/menu/white-peach-oolong.jpg",
    nutrition: null,
  },
  {
    id: "berry-hibiscus",
    name: "Berry Hibiscus",
    nameKo: "베리 히비스커스",
    category: "beverage",
    image: "/images/menu/berry-hibiscus.jpg",
    nutrition: { calories: 9.8, sodium: 11.5, sugar: 0.0, saturatedFat: 0.0, protein: 0.0, caffeine: 0.4, allergens: null },
  },
  {
    id: "seolhyang-strawberry-latte",
    name: "Seolhyang Strawberry Latte",
    nameKo: "설향 딸기 라떼",
    category: "beverage",
    image: "/images/menu/seolhyang-strawberry-latte.jpg",
    nutrition: { calories: 202.0, sodium: 89.2, sugar: 29.3, saturatedFat: 3.6, protein: 4.4, caffeine: null, allergens: "우유" },
  },
  {
    id: "pure-milk",
    name: "Pure Milk",
    nameKo: "순수 우유",
    category: "beverage",
    image: "/images/menu/pure-milk.jpg",
    nutrition: { calories: 149.5, sodium: 115.0, sugar: 11.5, saturatedFat: 6.2, protein: 6.9, caffeine: null, allergens: "우유" },
  },
  {
    id: "apple-mango-iced-tea",
    name: "Apple Mango Iced Tea",
    nameKo: "애플망고 아이스 티",
    category: "beverage",
    image: "/images/menu/apple-mango-iced-tea.jpg",
    nutrition: { calories: 184.7, sodium: 35.5, sugar: 44.4, saturatedFat: 0.0, protein: 0.4, caffeine: null, allergens: "복숭아/아황산류" },
  },
  {
    id: "yeongam-sweet-potato-latte",
    name: "Yeongam Sweet Potato Latte",
    nameKo: "영암 고구마 라떼",
    category: "beverage",
    image: "/images/menu/yeongam-sweet-potato-latte.jpg",
    nutrition: { calories: 259.7, sodium: 72.8, sugar: 30.2, saturatedFat: 3.6, protein: 5.8, caffeine: null, allergens: "우유/대두" },
  },
  {
    id: "grapefruit-ade",
    name: "Grapefruit Ade",
    nameKo: "자몽 에이드",
    category: "beverage",
    image: "/images/menu/grapefruit-ade.jpg",
    nutrition: { calories: 175.7, sodium: 18.2, sugar: 37.7, saturatedFat: 0.0, protein: 0.8, caffeine: null, allergens: null },
  },
  {
    id: "zero-peach-iced-tea",
    name: "Zero Peach Iced Tea",
    nameKo: "제로 복숭아 아이스티",
    category: "beverage",
    image: "/images/menu/zero-peach-iced-tea.jpg",
    nutrition: { calories: 14.0, sodium: 10.2, sugar: 0.4, saturatedFat: 0.0, protein: 0.0, caffeine: 15.1, allergens: "복숭아" },
  },
  {
    id: "jeju-matcha-latte",
    name: "Jeju Matcha Latte",
    nameKo: "제주 말차 라떼",
    category: "beverage",
    image: "/images/menu/jeju-matcha-latte.jpg",
    nutrition: { calories: 433.4, sodium: 148.3, sugar: 46.6, saturatedFat: 8.4, protein: 15.1, caffeine: 180.7, allergens: "우유/대두" },
  },
  {
    id: "jeju-misutgaru",
    name: "Jeju Misutgaru",
    nameKo: "제주 미숫가루",
    category: "beverage",
    image: "/images/menu/jeju-misutgaru.jpg",
    nutrition: { calories: 277.1, sodium: 72.8, sugar: 28.9, saturatedFat: 2.7, protein: 8.0, caffeine: null, allergens: "우유/대두" },
  },
  {
    id: "jeju-matcha-bubble-tea",
    name: "Jeju Matcha Bubble Tea",
    nameKo: "제주 말차 버블티",
    category: "beverage",
    image: "/images/menu/jeju-matcha-bubble-tea.jpg",
    nutrition: { calories: 472.2, sodium: 140.3, sugar: 44.0, saturatedFat: 8.4, protein: 12.0, caffeine: 155.0, allergens: "우유/대두" },
  },
  {
    id: "ginger-pear-tea",
    name: "Ginger Pear Tea",
    nameKo: "진저 배 티",
    category: "beverage",
    image: "/images/menu/ginger-pear-tea.jpg",
    nutrition: { calories: 145.6, sodium: 52.8, sugar: 34.6, saturatedFat: 0.0, protein: 0.4, caffeine: null, allergens: null },
  },
  {
    id: "green-grape-ade",
    name: "Green Grape Ade",
    nameKo: "청포도 에이드",
    category: "beverage",
    image: "/images/menu/green-grape-ade.jpg",
    nutrition: { calories: 163.4, sodium: 28.0, sugar: 27.1, saturatedFat: 0.0, protein: 0.4, caffeine: null, allergens: null },
  },
  {
    id: "peach-boy",
    name: "Peach Boy",
    nameKo: "피치보이",
    category: "beverage",
    image: "/images/menu/peach-boy.jpg",
    nutrition: null,
  },
  {
    id: "honey-chamomile",
    name: "Honey Chamomile",
    nameKo: "허니 캐모마일",
    category: "beverage",
    image: "/images/menu/honey-chamomile.jpg",
    nutrition: { calories: 3.6, sodium: 16.0, sugar: 0.0, saturatedFat: 0.0, protein: 0.0, caffeine: null, allergens: null },
  },
  {
    id: "black-sugar-bubble-ice-cream-ic",
    name: "Black Sugar Bubble Ice Cream Ic",
    nameKo: "흑당 버블 아이스크림",
    category: "beverage",
    image: "/images/menu/black-sugar-bubble-ice-cream-ic.jpg",
    nutrition: { calories: 311.2, sodium: 76.2, sugar: 22.4, saturatedFat: 8.3, protein: 4.6, caffeine: null, allergens: "우유/대두" },
  },
  // Blended
  {
    id: "honey-pear-smoothie",
    name: "Honey Pear Smoothie",
    nameKo: "꿀배 스무디",
    category: "blended",
    image: "/images/menu/honey-pear-smoothie.jpg",
    nutrition: { calories: 284.2, sodium: 87.0, sugar: 57.3, saturatedFat: 0.0, protein: 0.4, caffeine: null, allergens: null },
  },
  {
    id: "strawberry-banana-juice",
    name: "Strawberry Banana Juice",
    nameKo: "딸기 바나나 주스",
    category: "blended",
    image: "/images/menu/strawberry-banana-juice.jpg",
    nutrition: { calories: 302.8, sodium: 83.5, sugar: 51.1, saturatedFat: 4.0, protein: 7.5, caffeine: null, allergens: "우유" },
  },
  {
    id: "strawberry-shake",
    name: "Strawberry Shake",
    nameKo: "딸기 쉐이크",
    category: "blended",
    image: "/images/menu/strawberry-shake.jpg",
    nutrition: { calories: 444.9, sodium: 213.6, sugar: 49.7, saturatedFat: 5.3, protein: 4.0, caffeine: null, allergens: "우유/대두/아황산류" },
  },
  {
    id: "strawberry-yogurt-smoothie",
    name: "Strawberry Yogurt Smoothie",
    nameKo: "딸기 요거트 스무디",
    category: "blended",
    image: "/images/menu/strawberry-yogurt-smoothie.jpg",
    nutrition: { calories: 351.2, sodium: 68.4, sugar: 65.3, saturatedFat: 1.8, protein: 5.8, caffeine: null, allergens: "우유" },
  },
  {
    id: "strawberry-yuzu-smoothie",
    name: "Strawberry Yuzu Smoothie",
    nameKo: "딸기 유자 스무디",
    category: "blended",
    image: "/images/menu/strawberry-yuzu-smoothie.jpg",
    nutrition: { calories: 341.0, sodium: 52.4, sugar: 82.1, saturatedFat: 0.0, protein: 0.4, caffeine: null, allergens: null },
  },
  {
    id: "rice-shake",
    name: "Rice Shake",
    nameKo: "라이스 쉐이크",
    category: "blended",
    image: "/images/menu/rice-shake.jpg",
    nutrition: { calories: 485.8, sodium: 216.7, sugar: 33.3, saturatedFat: 4.9, protein: 4.4, caffeine: null, allergens: "우유/대두" },
  },
  {
    id: "red-grapefruit-smoothie",
    name: "Red Grapefruit Smoothie",
    nameKo: "레드자몽 스무디",
    category: "blended",
    image: "/images/menu/red-grapefruit-smoothie.jpg",
    nutrition: { calories: 262.9, sodium: 21.8, sugar: 62.2, saturatedFat: 0.0, protein: 0.9, caffeine: null, allergens: null },
  },
  {
    id: "real-watermelon-juice",
    name: "Real Watermelon Juice",
    nameKo: "리얼 수박 수즈",
    category: "blended",
    image: "/images/menu/real-watermelon-juice.jpg",
    nutrition: { calories: 142.1, sodium: 5.8, sugar: 26.2, saturatedFat: 0.0, protein: 1.3, caffeine: null, allergens: null },
  },
  {
    id: "mango-banana-smoothie",
    name: "Mango Banana Smoothie",
    nameKo: "망고 바나나 스무디",
    category: "blended",
    image: "/images/menu/mango-banana-smoothie.jpg",
    nutrition: { calories: 220.2, sodium: 22.6, sugar: 51.1, saturatedFat: 0.0, protein: 0.9, caffeine: null, allergens: null },
  },
  {
    id: "mango-yogurt-smoothie",
    name: "Mango Yogurt Smoothie",
    nameKo: "망고 요거트 스무디",
    category: "blended",
    image: "/images/menu/mango-yogurt-smoothie.jpg",
    nutrition: { calories: 349.0, sodium: 67.0, sugar: 62.6, saturatedFat: 1.3, protein: 4.4, caffeine: null, allergens: "우유" },
  },
  {
    id: "mint-choco-frappe",
    name: "Mint Choco Frappe",
    nameKo: "민트 초코 프라페",
    category: "blended",
    image: "/images/menu/mint-choco-frappe.jpg",
    nutrition: { calories: 352.1, sodium: 143.0, sugar: 59.9, saturatedFat: 3.6, protein: 6.7, caffeine: 25.3, allergens: "우유/대두" },
  },
  {
    id: "milk-shake",
    name: "Milk Shake",
    nameKo: "밀크쉐이크",
    category: "blended",
    image: "/images/menu/milk-shake.jpg",
    nutrition: { calories: 486.6, sodium: 153.2, sugar: 59.9, saturatedFat: 12.0, protein: 3.1, caffeine: null, allergens: "우유/대두" },
  },
  {
    id: "blueberry-yogurt-smoothie",
    name: "Blueberry Yogurt Smoothie",
    nameKo: "블루베리 요거트 스무디",
    category: "blended",
    image: "/images/menu/blueberry-yogurt-smoothie.jpg",
    nutrition: { calories: 389.8, sodium: 66.2, sugar: 63.9, saturatedFat: 1.8, protein: 5.3, caffeine: null, allergens: "우유" },
  },
  {
    id: "jeju-matcha-frappe",
    name: "Jeju Matcha Frappe",
    nameKo: "제주 말차 프라페",
    category: "blended",
    image: "/images/menu/jeju-matcha-frappe.jpg",
    nutrition: { calories: 766.9, sodium: 186.9, sugar: 116.3, saturatedFat: 12.9, protein: 14.2, caffeine: 217.6, allergens: "우유/대두" },
  },
  {
    id: "jeju-lemon-smoothie",
    name: "Jeju Lemon Smoothie",
    nameKo: "제주 레몬 스무디",
    category: "blended",
    image: "/images/menu/jeju-lemon-smoothie.jpg",
    nutrition: { calories: 225.6, sodium: 19.5, sugar: 48.8, saturatedFat: 0.0, protein: 1.8, caffeine: null, allergens: null },
  },
  {
    id: "green-grape-smoothie",
    name: "Green Grape Smoothie",
    nameKo: "청포도 스무디",
    category: "blended",
    image: "/images/menu/green-grape-smoothie.jpg",
    nutrition: { calories: 312.6, sodium: 40.0, sugar: 72.8, saturatedFat: 0.0, protein: 0.4, caffeine: null, allergens: null },
  },
  {
    id: "choco-banana-smoothie",
    name: "Choco Banana Smoothie",
    nameKo: "초코 바나나 스무디",
    category: "blended",
    image: "/images/menu/choco-banana-smoothie.jpg",
    nutrition: { calories: 342.3, sodium: 129.2, sugar: 48.0, saturatedFat: 6.2, protein: 6.7, caffeine: 7.1, allergens: "우유/대두" },
  },
  {
    id: "choco-shake",
    name: "Choco Shake",
    nameKo: "초코 쉐이크",
    category: "blended",
    image: "/images/menu/choco-shake.jpg",
    nutrition: { calories: 383.6, sodium: 182.9, sugar: 47.1, saturatedFat: 8.9, protein: 8.0, caffeine: 11.5, allergens: "우유/대두" },
  },
  {
    id: "coffee-shake",
    name: "Coffee Shake",
    nameKo: "커피 쉐이크",
    category: "blended",
    image: "/images/menu/coffee-shake.jpg",
    nutrition: { calories: 323.2, sodium: 103.0, sugar: 63.9, saturatedFat: 3.1, protein: 4.9, caffeine: 215.3, allergens: "우유/대두" },
  },
  {
    id: "cup-bingsu",
    name: "Cup Bingsu",
    nameKo: "컵빙수",
    category: "blended",
    image: "/images/menu/cup-bingsu.jpg",
    nutrition: { calories: 413.0, sodium: 139.0, sugar: 61.3, saturatedFat: 4.0, protein: 3.1, caffeine: null, allergens: "우유/대두" },
  },
  {
    id: "plain-yogurt-smoothie",
    name: "Plain Yogurt Smoothie",
    nameKo: "플레인 요거트 스무디",
    category: "blended",
    image: "/images/menu/plain-yogurt-smoothie.jpg",
    nutrition: { calories: 392.5, sodium: 83.0, sugar: 65.7, saturatedFat: 0.9, protein: 5.8, caffeine: null, allergens: "우유" },
  },
  {
    id: "hadong-plum-smoothie",
    name: "Hadong Plum Smoothie",
    nameKo: "하동 매실 스무디",
    category: "blended",
    image: "/images/menu/hadong-plum-smoothie.jpg",
    nutrition: { calories: 289.5, sodium: 51.5, sugar: 59.5, saturatedFat: 0.0, protein: 1.8, caffeine: null, allergens: null },
  },
  // Bottle
  {
    id: "bottle-honey-grapefruit-tea",
    name: "Bottle Honey Grapefruit Tea",
    nameKo: "보틀 꿀 자몽 티",
    category: "bottle",
    image: "/images/menu/bottle-honey-grapefruit-tea.jpg",
    nutrition: null,
  },
  {
    id: "bottle-double-choco-latte",
    name: "Bottle Double Choco Latte",
    nameKo: "보틀 더블 초코 라떼",
    category: "bottle",
    image: "/images/menu/bottle-double-choco-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-dolce-latte",
    name: "Bottle Dolce Latte",
    nameKo: "보틀 돌체 라떼",
    category: "bottle",
    image: "/images/menu/bottle-dolce-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-strawberry-iced-tea",
    name: "Bottle Strawberry Iced Tea",
    nameKo: "보틀 딸기 아이스 티",
    category: "bottle",
    image: "/images/menu/bottle-strawberry-iced-tea.jpg",
    nutrition: null,
  },
  {
    id: "bottle-lemon-earl-grey-tea",
    name: "Bottle Lemon Earl Grey Tea",
    nameKo: "보틀 레몬 얼그레이 티",
    category: "bottle",
    image: "/images/menu/bottle-lemon-earl-grey-tea.jpg",
    nutrition: null,
  },
  {
    id: "bottle-lemon-ade",
    name: "Bottle Lemon Ade",
    nameKo: "보틀 레몬 에이드",
    category: "bottle",
    image: "/images/menu/bottle-lemon-ade.jpg",
    nutrition: null,
  },
  {
    id: "bottle-lemon-yuzu-tea",
    name: "Bottle Lemon Yuzu Tea",
    nameKo: "보틀 레몬 유자 티",
    category: "bottle",
    image: "/images/menu/bottle-lemon-yuzu-tea.jpg",
    nutrition: null,
  },
  {
    id: "bottle-royal-milk-tea",
    name: "Bottle Royal Milk Tea",
    nameKo: "보틀 로얄 밀크 티",
    category: "bottle",
    image: "/images/menu/bottle-royal-milk-tea.jpg",
    nutrition: null,
  },
  {
    id: "bottle-mango-latte",
    name: "Bottle Mango Latte",
    nameKo: "보틀 망고 라떼",
    category: "bottle",
    image: "/images/menu/bottle-mango-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-banana-oat-latte",
    name: "Bottle Banana Oat Latte",
    nameKo: "보틀 바나나 오트 라떼",
    category: "bottle",
    image: "/images/menu/bottle-banana-oat-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-vanilla-bean-latte",
    name: "Bottle Vanilla Bean Latte",
    nameKo: "보틀 바닐라 빈 라떼",
    category: "bottle",
    image: "/images/menu/bottle-vanilla-bean-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-valrhona-chocolate",
    name: "Bottle Valrhona Chocolate",
    nameKo: "보틀 발로나 초콜릿",
    category: "bottle",
    image: "/images/menu/bottle-valrhona-chocolate.jpg",
    nutrition: null,
  },
  {
    id: "bottle-berry-hibiscus",
    name: "Bottle Berry Hibiscus",
    nameKo: "보틀 베리 히비스커스",
    category: "bottle",
    image: "/images/menu/bottle-berry-hibiscus.jpg",
    nutrition: null,
  },
  {
    id: "bottle-barley-misutgaru",
    name: "Bottle Barley Misutgaru",
    nameKo: "보틀 보리 미숫가루",
    category: "bottle",
    image: "/images/menu/bottle-barley-misutgaru.jpg",
    nutrition: null,
  },
  {
    id: "bottle-seolhyang-strawberry-latte",
    name: "Bottle Seolhyang Strawberry Latte",
    nameKo: "보틀 설향 딸기 라떼",
    category: "bottle",
    image: "/images/menu/bottle-seolhyang-strawberry-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-pure-milk",
    name: "Bottle Pure Milk",
    nameKo: "보틀 순수 우유",
    category: "bottle",
    image: "/images/menu/bottle-pure-milk.jpg",
    nutrition: null,
  },
  {
    id: "bottle-cinnamon-cafe-latte",
    name: "Bottle Cinnamon Cafe Latte",
    nameKo: "보틀 시나몬 카페 라떼",
    category: "bottle",
    image: "/images/menu/bottle-cinnamon-cafe-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-americano",
    name: "Bottle Americano",
    nameKo: "보틀 아메리카노",
    category: "bottle",
    image: "/images/menu/bottle-americano.jpg",
    nutrition: null,
  },
  {
    id: "bottle-ah-shot-chu",
    name: "Bottle Ah Shot Chu",
    nameKo: "보틀 아샷추",
    category: "bottle",
    image: "/images/menu/bottle-ah-shot-chu.jpg",
    nutrition: null,
  },
  {
    id: "bottle-apple-mango-iced-tea",
    name: "Bottle Apple Mango Iced Tea",
    nameKo: "보틀 애플망고 아이스 티",
    category: "bottle",
    image: "/images/menu/bottle-apple-mango-iced-tea.jpg",
    nutrition: null,
  },
  {
    id: "bottle-earl-grey-vanilla-tea-latte",
    name: "Bottle Earl Grey Vanilla Tea Latte",
    nameKo: "보틀 얼그레이 바닐라 티 라떼",
    category: "bottle",
    image: "/images/menu/bottle-earl-grey-vanilla-tea-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-sweet-potato-latte",
    name: "Bottle Sweet Potato Latte",
    nameKo: "보틀 영암 고구마 라떼",
    category: "bottle",
    image: "/images/menu/bottle-sweet-potato-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-grapefruit-ade",
    name: "Bottle Grapefruit Ade",
    nameKo: "보틀 자몽 에이드",
    category: "bottle",
    image: "/images/menu/bottle-grapefruit-ade.jpg",
    nutrition: null,
  },
  {
    id: "bottle-jeju-matcha-latte",
    name: "Bottle Jeju Matcha Latte",
    nameKo: "보틀 제주 말차 라떼",
    category: "bottle",
    image: "/images/menu/bottle-jeju-matcha-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-jeju-matcha-cafe-latte",
    name: "Bottle Jeju Matcha Cafe Latte",
    nameKo: "보틀 제주 말차 카페 라떼",
    category: "bottle",
    image: "/images/menu/bottle-jeju-matcha-cafe-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-jeju-hojicha",
    name: "Bottle Jeju Hojicha",
    nameKo: "보틀 제주 호지차",
    category: "bottle",
    image: "/images/menu/bottle-jeju-hojicha.jpg",
    nutrition: null,
  },
  {
    id: "bottle-ginger-pear-tea",
    name: "Bottle Ginger Pear Tea",
    nameKo: "보틀 진저 배 티",
    category: "bottle",
    image: "/images/menu/bottle-ginger-pear-tea.jpg",
    nutrition: null,
  },
  {
    id: "bottle-green-grape-ade",
    name: "Bottle Green Grape Ade",
    nameKo: "보틀 청포도 에이드",
    category: "bottle",
    image: "/images/menu/bottle-green-grape-ade.jpg",
    nutrition: null,
  },
  {
    id: "bottle-caramel-macchiato",
    name: "Bottle Caramel Macchiato",
    nameKo: "보틀 카라멜 마끼야또",
    category: "bottle",
    image: "/images/menu/bottle-caramel-macchiato.jpg",
    nutrition: null,
  },
  {
    id: "bottle-cafe-latte",
    name: "Bottle Cafe Latte",
    nameKo: "보틀 카페 라떼",
    category: "bottle",
    image: "/images/menu/bottle-cafe-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-cafe-mocha",
    name: "Bottle Cafe Mocha",
    nameKo: "보틀 카페 모카",
    category: "bottle",
    image: "/images/menu/bottle-cafe-mocha.jpg",
    nutrition: null,
  },
  {
    id: "bottle-cold-brew-dolce-latte",
    name: "Bottle Cold Brew Dolce Latte",
    nameKo: "보틀 콜드 브루 돌체 라떼",
    category: "bottle",
    image: "/images/menu/bottle-cold-brew-dolce-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-cold-brew-americano",
    name: "Bottle Cold Brew Americano",
    nameKo: "보틀 콜드 브루 아메리카노",
    category: "bottle",
    image: "/images/menu/bottle-cold-brew-americano.jpg",
    nutrition: null,
  },
  {
    id: "bottle-cold-brew-cafe-latte",
    name: "Bottle Cold Brew Cafe Latte",
    nameKo: "보틀 콜드 브루 카페 라떼",
    category: "bottle",
    image: "/images/menu/bottle-cold-brew-cafe-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-toffee-nut-latte",
    name: "Bottle Toffee Nut Latte",
    nameKo: "보틀 토피넛 라떼",
    category: "bottle",
    image: "/images/menu/bottle-toffee-nut-latte.jpg",
    nutrition: null,
  },
  {
    id: "bottle-peppermint",
    name: "Bottle Peppermint",
    nameKo: "보틀 페퍼민트",
    category: "bottle",
    image: "/images/menu/bottle-peppermint.jpg",
    nutrition: null,
  },
  {
    id: "bottle-honey-chamomile",
    name: "Bottle Honey Chamomile",
    nameKo: "보틀 허니 캐모마일",
    category: "bottle",
    image: "/images/menu/bottle-honey-chamomile.jpg",
    nutrition: null,
  },
  {
    id: "bottle-white-americano",
    name: "Bottle White Americano",
    nameKo: "보틀 화이트 아메리카노",
    category: "bottle",
    image: "/images/menu/bottle-white-americano.jpg",
    nutrition: null,
  },
  // Bakery
  {
    id: "canele",
    name: "Canele",
    nameKo: "까눌레",
    category: "bakery",
    image: "/images/menu/canele.jpg",
    nutrition: { calories: 288, sodium: 33, sugar: 19, saturatedFat: 1.0, protein: 5, caffeine: null, allergens: "밀/계란/견과류" },
  },
  {
    id: "dubai-choco-financier",
    name: "Dubai Choco Financier",
    nameKo: "두바이 초코 휘낭시에",
    category: "bakery",
    image: "/images/menu/dubai-choco-financier.jpg",
    nutrition: { calories: 271, sodium: 95, sugar: 17, saturatedFat: 5, protein: 4, caffeine: null, allergens: null },
  },
  {
    id: "strawberry-donut",
    name: "Strawberry Donut",
    nameKo: "딸기 도넛",
    category: "bakery",
    image: "/images/menu/strawberry-donut.jpg",
    nutrition: null,
  },
  {
    id: "lemon-donut",
    name: "Lemon Donut",
    nameKo: "레몬 도넛",
    category: "bakery",
    image: "/images/menu/lemon-donut.jpg",
    nutrition: null,
  },
  {
    id: "lemon-cake",
    name: "Lemon Cake",
    nameKo: "레몬케이크",
    category: "bakery",
    image: "/images/menu/lemon-cake.jpg",
    nutrition: null,
  },
  {
    id: "roasted-macadamia-financier",
    name: "Roasted Macadamia Financier",
    nameKo: "로스티드 마카다미아 휘낭시에",
    category: "bakery",
    image: "/images/menu/roasted-macadamia-financier.jpg",
    nutrition: { calories: 234, sodium: 120, sugar: 12, saturatedFat: 2.9, protein: 3, caffeine: null, allergens: null },
  },
  {
    id: "fig-cream-cheese-baton-financier",
    name: "Fig Cream Cheese Baton Financier",
    nameKo: "무화과크림치즈 바통휘낭시에",
    category: "bakery",
    image: "/images/menu/fig-cream-cheese-baton-financier.jpg",
    nutrition: null,
  },
  {
    id: "milk-scone",
    name: "Milk Scone",
    nameKo: "밀크 스콘",
    category: "bakery",
    image: "/images/menu/milk-scone.jpg",
    nutrition: { calories: 359, sodium: 277, sugar: 12, saturatedFat: 9.0, protein: 5, caffeine: null, allergens: "밀/계란/견과류" },
  },
  {
    id: "vanilla-donut",
    name: "Vanilla Donut",
    nameKo: "바닐라 도넛",
    category: "bakery",
    image: "/images/menu/vanilla-donut.jpg",
    nutrition: null,
  },
  {
    id: "valrhona-smore-cookie",
    name: "Valrhona Smore Cookie",
    nameKo: "발로나 스모어 쿠키",
    category: "bakery",
    image: "/images/menu/valrhona-smore-cookie.jpg",
    nutrition: { calories: 622, sodium: 116, sugar: 39, saturatedFat: 10, protein: 6, caffeine: null, allergens: "밀/계란/견과류" },
  },
  {
    id: "bacon-egg-mayo-bread",
    name: "Bacon Egg Mayo Bread",
    nameKo: "베이컨 에그마요 빵",
    category: "bakery",
    image: "/images/menu/bacon-egg-mayo-bread.jpg",
    nutrition: null,
  },
  {
    id: "ssuk-red-bean-smore-cookie",
    name: "Ssuk Red Bean Smore Cookie",
    nameKo: "쑥단팥 스모어쿠키",
    category: "bakery",
    image: "/images/menu/ssuk-red-bean-smore-cookie.jpg",
    nutrition: { calories: 571, sodium: 158, sugar: 38, saturatedFat: 10, protein: 8, caffeine: null, allergens: "밀/계란/견과류" },
  },
  {
    id: "almond-biscotti",
    name: "Almond Biscotti",
    nameKo: "아몬드 비스코티",
    category: "bakery",
    image: "/images/menu/almond-biscotti.jpg",
    nutrition: { calories: 77, sodium: 32, sugar: 3, saturatedFat: 1, protein: 2, caffeine: null, allergens: "밀/계란/견과류" },
  },
  {
    id: "yakgwa-baton-financier",
    name: "Yakgwa Baton Financier",
    nameKo: "약과 바통휘낭시에",
    category: "bakery",
    image: "/images/menu/yakgwa-baton-financier.jpg",
    nutrition: null,
  },
  {
    id: "earl-grey-baton-financier",
    name: "Earl Grey Baton Financier",
    nameKo: "얼그레이 바통휘낭시에",
    category: "bakery",
    image: "/images/menu/earl-grey-baton-financier.jpg",
    nutrition: null,
  },
  {
    id: "milk-donut",
    name: "Milk Donut",
    nameKo: "우유 도넛",
    category: "bakery",
    image: "/images/menu/milk-donut.jpg",
    nutrition: null,
  },
  {
    id: "walnut-choco-cookie",
    name: "Walnut Choco Cookie",
    nameKo: "월넛 초코 쿠키",
    category: "bakery",
    image: "/images/menu/walnut-choco-cookie.jpg",
    nutrition: { calories: 546, sodium: 152, sugar: 24, saturatedFat: 10, protein: 7, caffeine: null, allergens: "밀/계란/견과류" },
  },
  {
    id: "choco-donut",
    name: "Choco Donut",
    nameKo: "초코 도넛",
    category: "bakery",
    image: "/images/menu/choco-donut.jpg",
    nutrition: null,
  },
  {
    id: "chocochip-biscotti",
    name: "Chocochip Biscotti",
    nameKo: "초코칩 비스코티",
    category: "bakery",
    image: "/images/menu/chocochip-biscotti.jpg",
    nutrition: { calories: 76, sodium: 32, sugar: 5, saturatedFat: 2, protein: 1, caffeine: null, allergens: "밀/계란/견과류" },
  },
  {
    id: "churros-baton-financier",
    name: "Churros Baton Financier",
    nameKo: "츄러스 바통휘낭시에",
    category: "bakery",
    image: "/images/menu/churros-baton-financier.jpg",
    nutrition: null,
  },
  {
    id: "cookies-cream-donut",
    name: "Cookies Cream Donut",
    nameKo: "쿠키앤 크림 도넛",
    category: "bakery",
    image: "/images/menu/cookies-cream-donut.jpg",
    nutrition: null,
  },
  {
    id: "famille-kahlua-macchiato",
    name: "Famille Kahlua Macchiato",
    nameKo: "깔루아 마키아토",
    category: "bakery",
    image: "/images/menu/famille-kahlua-macchiato.jpg",
    nutrition: null,
  },
  {
    id: "famille-ny-cheesecake",
    name: "Famille Ny Cheesecake",
    nameKo: "뉴욕 치즈케이크",
    category: "bakery",
    image: "/images/menu/famille-ny-cheesecake.jpg",
    nutrition: null,
  },
  {
    id: "famille-strawberry-granola-cookie",
    name: "Famille Strawberry Granola Cookie",
    nameKo: "딸기 그래놀라 쫀득쿠키",
    category: "bakery",
    image: "/images/menu/famille-strawberry-granola-cookie.jpg",
    nutrition: null,
  },
  {
    id: "famille-strawberry-macaron",
    name: "Famille Strawberry Macaron",
    nameKo: "딸기 마카롱",
    category: "bakery",
    image: "/images/menu/famille-strawberry-macaron.jpg",
    nutrition: null,
  },
  {
    id: "famille-strawberry-cookies-cream-cookie",
    name: "Famille Strawberry Cookies Cream Cookie",
    nameKo: "딸기 쿠키앤크림 쫀득쿠키",
    category: "bakery",
    image: "/images/menu/famille-strawberry-cookies-cream-cookie.jpg",
    nutrition: null,
  },
  {
    id: "famille-milk-crepe",
    name: "Famille Milk Crepe",
    nameKo: "밀크 크레이프",
    category: "bakery",
    image: "/images/menu/famille-milk-crepe.jpg",
    nutrition: null,
  },
  {
    id: "famille-bulgogi-ciabatta",
    name: "Famille Bulgogi Ciabatta",
    nameKo: "불고기 치아바타",
    category: "bakery",
    image: "/images/menu/famille-bulgogi-ciabatta.jpg",
    nutrition: null,
  },
  {
    id: "famille-black-forest-cream",
    name: "Famille Black Forest Cream",
    nameKo: "블랙 포레스트 생크림",
    category: "bakery",
    image: "/images/menu/famille-black-forest-cream.jpg",
    nutrition: null,
  },
  {
    id: "famille-cream-castella",
    name: "Famille Cream Castella",
    nameKo: "생크림 카스테라",
    category: "bakery",
    image: "/images/menu/famille-cream-castella.jpg",
    nutrition: null,
  },
  {
    id: "famille-devils-choco-cake",
    name: "Famille Devils Choco Cake",
    nameKo: "악마의 초코 케익",
    category: "bakery",
    image: "/images/menu/famille-devils-choco-cake.jpg",
    nutrition: null,
  },
  {
    id: "famille-onion-bagel",
    name: "Famille Onion Bagel",
    nameKo: "어니언 베이글",
    category: "bakery",
    image: "/images/menu/famille-onion-bagel.jpg",
    nutrition: null,
  },
  {
    id: "famille-condensed-milk-morning",
    name: "Famille Condensed Milk Morning",
    nameKo: "연유 밀크 모닝",
    category: "bakery",
    image: "/images/menu/famille-condensed-milk-morning.jpg",
    nutrition: null,
  },
  {
    id: "famille-original-bun",
    name: "Famille Original Bun",
    nameKo: "오리지날번",
    category: "bakery",
    image: "/images/menu/famille-original-bun.jpg",
    nutrition: null,
  },
  {
    id: "famille-injeolmi-macaron",
    name: "Famille Injeolmi Macaron",
    nameKo: "인절미 마카롱",
    category: "bakery",
    image: "/images/menu/famille-injeolmi-macaron.jpg",
    nutrition: null,
  },
  {
    id: "famille-english-muffin-sandwich",
    name: "Famille English Muffin Sandwich",
    nameKo: "잉글리쉬 머핀 샌드위치",
    category: "bakery",
    image: "/images/menu/famille-english-muffin-sandwich.jpg",
    nutrition: null,
  },
  {
    id: "famille-choco-macaron",
    name: "Famille Choco Macaron",
    nameKo: "초코 마카롱",
    category: "bakery",
    image: "/images/menu/famille-choco-macaron.jpg",
    nutrition: null,
  },
  {
    id: "famille-cheese-bagel",
    name: "Famille Cheese Bagel",
    nameKo: "치즈 베이글",
    category: "bakery",
    image: "/images/menu/famille-cheese-bagel.jpg",
    nutrition: null,
  },
  {
    id: "famille-croque-monsieur",
    name: "Famille Croque Monsieur",
    nameKo: "크로크무슈",
    category: "bakery",
    image: "/images/menu/famille-croque-monsieur.jpg",
    nutrition: null,
  },
  {
    id: "famille-cream-red-bean-bread",
    name: "Famille Cream Red Bean Bread",
    nameKo: "크림 단팥빵",
    category: "bakery",
    image: "/images/menu/famille-cream-red-bean-bread.jpg",
    nutrition: null,
  },
  {
    id: "famille-creme-brulee-macaron",
    name: "Famille Creme Brulee Macaron",
    nameKo: "크림브륄레 마카롱",
    category: "bakery",
    image: "/images/menu/famille-creme-brulee-macaron.jpg",
    nutrition: null,
  },
  {
    id: "famille-tiramisu",
    name: "Famille Tiramisu",
    nameKo: "티라미수",
    category: "bakery",
    image: "/images/menu/famille-tiramisu.jpg",
    nutrition: null,
  },
  {
    id: "famille-plain-bagel",
    name: "Famille Plain Bagel",
    nameKo: "플레인 베이글",
    category: "bakery",
    image: "/images/menu/famille-plain-bagel.jpg",
    nutrition: null,
  },
  {
    id: "famille-ham-cheese-taiwan-sandwich",
    name: "Famille Ham Cheese Taiwan Sandwich",
    nameKo: "햄치즈 대만 샌드위치",
    category: "bakery",
    image: "/images/menu/famille-ham-cheese-taiwan-sandwich.jpg",
    nutrition: null,
  },
  {
    id: "pearl-salt-financier",
    name: "Pearl Salt Financier",
    nameKo: "펄솔트 휘낭시에",
    category: "bakery",
    image: "/images/menu/pearl-salt-financier.jpg",
    nutrition: { calories: 122, sodium: 65, sugar: 9, saturatedFat: 2.5, protein: 2, caffeine: null, allergens: null },
  },
  {
    id: "honey-crispy-financier",
    name: "Honey Crispy Financier",
    nameKo: "허니 크리스피 휘낭시에",
    category: "bakery",
    image: "/images/menu/honey-crispy-financier.jpg",
    nutrition: { calories: 189, sodium: 65, sugar: 13, saturatedFat: 3.1, protein: 3, caffeine: null, allergens: null },
  },
  // Ice-cream
  {
    id: "strawberry-ice-cream",
    name: "Strawberry Ice Cream",
    nameKo: "딸기 아이스크림",
    category: "ice-cream",
    image: "/images/menu/strawberry-ice-cream.jpg",
    nutrition: { calories: 384.8, sodium: 111.4, sugar: 48.9, saturatedFat: 10.4, protein: 5.4, caffeine: null, allergens: "우유/대두" },
  },
  {
    id: "strawberry-cookie-ice-cream-frappe",
    name: "Strawberry Cookie Ice Cream Frappe",
    nameKo: "딸기 쿠키 아이스크림 프라페",
    category: "ice-cream",
    image: "/images/menu/strawberry-cookie-ice-cream-frappe.jpg",
    nutrition: { calories: 517.3, sodium: 276.2, sugar: 67.0, saturatedFat: 5.3, protein: 5.3, caffeine: null, allergens: "우유/대두/아황산류" },
  },
  {
    id: "matcha-ice-cream",
    name: "Matcha Ice Cream",
    nameKo: "말차 아이스크림",
    category: "ice-cream",
    image: "/images/menu/matcha-ice-cream.jpg",
    nutrition: { calories: 786.4, sodium: 262.8, sugar: 68.4, saturatedFat: 24.4, protein: 13.3, caffeine: 93.2, allergens: "우유/대두" },
  },
  {
    id: "matcha-cookie-ice-cream-frappe",
    name: "Matcha Cookie Ice Cream Frappe",
    nameKo: "말차 쿠키 아이스크림 프라페",
    category: "ice-cream",
    image: "/images/menu/matcha-cookie-ice-cream-frappe.jpg",
    nutrition: { calories: 559.9, sodium: 180.7, sugar: 78.6, saturatedFat: 5.3, protein: 6.7, caffeine: 53.7, allergens: "우유/대두" },
  },
  {
    id: "black-cookie-ice-cream",
    name: "Black Cookie Ice Cream",
    nameKo: "블랙쿠키 아이스크림",
    category: "ice-cream",
    image: "/images/menu/black-cookie-ice-cream.jpg",
    nutrition: { calories: 483.6, sodium: 262.9, sugar: 42.0, saturatedFat: 12.4, protein: 7.0, caffeine: null, allergens: "우유/대두" },
  },
  {
    id: "soft-ice-cream",
    name: "Soft Ice Cream",
    nameKo: "소프트 아이스크림",
    category: "ice-cream",
    image: "/images/menu/soft-ice-cream.jpg",
    nutrition: { calories: 252.0, sodium: 56.0, sugar: 23.8, saturatedFat: 9.8, protein: 5.3, caffeine: null, allergens: "우유/대두" },
  },
  {
    id: "ice-cream-latte",
    name: "Ice Cream Latte",
    nameKo: "아이스크림 라떼",
    category: "ice-cream",
    image: "/images/menu/ice-cream-latte.jpg",
    nutrition: { calories: 362.7, sodium: 119.9, sugar: 42.2, saturatedFat: 10.2, protein: 7.5, caffeine: 147.0, allergens: "우유/대두" },
  },
  {
    id: "apple-mango-ice-cream",
    name: "Apple Mango Ice Cream",
    nameKo: "애플망고 아이스크림",
    category: "ice-cream",
    image: "/images/menu/apple-mango-ice-cream.jpg",
    nutrition: { calories: 390.4, sodium: 124.4, sugar: 47.4, saturatedFat: 11.0, protein: 6.0, caffeine: null, allergens: "우유/대두" },
  },
  {
    id: "espresso-ice-cream",
    name: "Espresso Ice Cream",
    nameKo: "에스프레소 아이스크림",
    category: "ice-cream",
    image: "/images/menu/espresso-ice-cream.jpg",
    nutrition: { calories: 255.3, sodium: 64.0, sugar: 17.2, saturatedFat: 8.8, protein: 5.5, caffeine: 124.0, allergens: "우유/대두" },
  },
  {
    id: "injeolmi-ice-cream",
    name: "Injeolmi Ice Cream",
    nameKo: "인절미 아이스크림",
    category: "ice-cream",
    image: "/images/menu/injeolmi-ice-cream.jpg",
    nutrition: { calories: 416.9, sodium: 138.7, sugar: 45.1, saturatedFat: 11.2, protein: 6.8, caffeine: null, allergens: "우유/대두" },
  },
  {
    id: "choco-ice-cream",
    name: "Choco Ice Cream",
    nameKo: "초코 아이스크림",
    category: "ice-cream",
    image: "/images/menu/choco-ice-cream.jpg",
    nutrition: { calories: 359.6, sodium: 132.5, sugar: 35.0, saturatedFat: 12.4, protein: 6.8, caffeine: 3.5, allergens: "우유/대두" },
  },
  {
    id: "black-sugar-bubble-ice-cream-ic",
    name: "Black Sugar Bubble Ice Cream Ic",
    nameKo: "흑당 버블 아이스크림",
    category: "ice-cream",
    image: "/images/menu/black-sugar-bubble-ice-cream-ic.jpg",
    nutrition: { calories: 311.2, sodium: 76.2, sugar: 22.4, saturatedFat: 8.3, protein: 4.6, caffeine: null, allergens: "우유/대두" },
  },
];
