import { MenuItem, MenuCategoryInfo } from "@/types";

export const MENU_CATEGORIES: MenuCategoryInfo[] = [
  { id: "coffee", label: "Coffee", labelKo: "커피" },
  { id: "beverage", label: "Beverage", labelKo: "음료" },
  { id: "blended", label: "Blended", labelKo: "블렌디드" },
  { id: "bottle", label: "Bottle", labelKo: "보틀" },
  { id: "bakery", label: "Bakery", labelKo: "베이커리" },
  { id: "ice-cream", label: "Ice-cream", labelKo: "아이스크림" },
  { id: "md", label: "MD", labelKo: "MD 상품" },
];

export const MENU_ITEMS: MenuItem[] = [
  // Coffee
  {
    id: "dolce-latte",
    name: "Dolce Latte",
    nameKo: "돌체 라떼",
    category: "coffee",
    image: "/images/menu/dolce-latte.jpg",
  },
  {
    id: "dolce-cold-brew-latte",
    name: "Dolce Cold Brew Latte",
    nameKo: "돌체 콜드브루 라떼",
    category: "coffee",
    image: "/images/menu/dolce-cold-brew-latte.jpg",
  },
  {
    id: "banana-cold-brew-oat-latte",
    name: "Banana Cold Brew Oat Latte",
    nameKo: "바나나 콜드브루 오트라떼",
    category: "coffee",
    image: "/images/menu/banana-cold-brew-oat-latte.jpg",
  },
  {
    id: "vanilla-bean-latte",
    name: "Vanilla Bean Latte",
    nameKo: "바닐라 빈 라떼",
    category: "coffee",
    image: "/images/menu/vanilla-bean-latte.jpg",
  },
  {
    id: "shaak-latte",
    name: "Shaak Latte",
    nameKo: "샥라떼",
    category: "coffee",
    image: "/images/menu/shaak-latte.jpg",
  },
  {
    id: "cinnamon-cafe-latte",
    name: "Cinnamon Cafe Latte",
    nameKo: "시나몬 카페 라떼",
    category: "coffee",
    image: "/images/menu/cinnamon-cafe-latte.jpg",
  },
  {
    id: "americano",
    name: "Americano",
    nameKo: "아메리카노",
    category: "coffee",
    image: "/images/menu/americano.jpg",
  },
  {
    id: "ah-shot-chu",
    name: "Ah Shot Chu",
    nameKo: "아샷추",
    category: "coffee",
    image: "/images/menu/ah-shot-chu.jpg",
  },
  {
    id: "espresso",
    name: "Espresso",
    nameKo: "에스프레소",
    category: "coffee",
    image: "/images/menu/espresso.jpg",
  },
  {
    id: "zero-vanilla-latte",
    name: "Zero Vanilla Latte",
    nameKo: "제로 바닐라 라떼",
    category: "coffee",
    image: "/images/menu/zero-vanilla-latte.jpg",
  },
  {
    id: "jeju-matcha-cafe-latte",
    name: "Jeju Matcha Cafe Latte",
    nameKo: "제주 말차 카페 라떼",
    category: "coffee",
    image: "/images/menu/jeju-matcha-cafe-latte.jpg",
  },
  {
    id: "caramel-macchiato",
    name: "Caramel Macchiato",
    nameKo: "카라멜 마끼야또",
    category: "coffee",
    image: "/images/menu/caramel-macchiato.jpg",
  },
  {
    id: "cafe-latte",
    name: "Cafe Latte",
    nameKo: "카페 라떼",
    category: "coffee",
    image: "/images/menu/cafe-latte.jpg",
  },
  {
    id: "cafe-mocha",
    name: "Cafe Mocha",
    nameKo: "카페 모카",
    category: "coffee",
    image: "/images/menu/cafe-mocha.jpg",
  },
  {
    id: "cafe-citrus",
    name: "Cafe Citrus",
    nameKo: "카페 시트러스",
    category: "coffee",
    image: "/images/menu/cafe-citrus.jpg",
  },
  {
    id: "cafe-pieno",
    name: "Cafe Pieno",
    nameKo: "카페 피에노",
    category: "coffee",
    image: "/images/menu/cafe-pieno.jpg",
  },
  {
    id: "cold-brew-latte",
    name: "Cold Brew Latte",
    nameKo: "콜드브루 라떼",
    category: "coffee",
    image: "/images/menu/cold-brew-latte.jpg",
  },
  {
    id: "cold-brew-americano",
    name: "Cold Brew Americano",
    nameKo: "콜드브루 아메리카노",
    category: "coffee",
    image: "/images/menu/cold-brew-americano.jpg",
  },
  {
    id: "peanut-latte",
    name: "Peanut Latte",
    nameKo: "피넛라떼",
    category: "coffee",
    image: "/images/menu/peanut-latte.jpg",
  },
  // Beverage
  {
    id: "golden-yuzu-beauty-elixir",
    name: "Golden Yuzu Beauty Elixir",
    nameKo: "골든유자 뷰티 엘릭서",
    category: "beverage",
    image: "/images/menu/golden-yuzu-beauty-elixir.jpg",
  },
  {
    id: "honey-grapefruit-tea",
    name: "Honey Grapefruit Tea",
    nameKo: "꿀 자몽 티",
    category: "beverage",
    image: "/images/menu/honey-grapefruit-tea.jpg",
  },
  {
    id: "double-choco-latte",
    name: "Double Choco Latte",
    nameKo: "더블 초코라떼",
    category: "beverage",
    image: "/images/menu/double-choco-latte.jpg",
  },
  {
    id: "double-choco-bubble-tea",
    name: "Double Choco Bubble Tea",
    nameKo: "더블 초코 버블티",
    category: "beverage",
    image: "/images/menu/double-choco-bubble-tea.jpg",
  },
  {
    id: "strawberry-iced-tea",
    name: "Strawberry Iced Tea",
    nameKo: "딸기 아이스 티",
    category: "beverage",
    image: "/images/menu/strawberry-iced-tea.jpg",
  },
  {
    id: "lemon-earl-grey-tea",
    name: "Lemon Earl Grey Tea",
    nameKo: "레몬 얼그레이 티",
    category: "beverage",
    image: "/images/menu/lemon-earl-grey-tea.jpg",
  },
  {
    id: "lemon-ade",
    name: "Lemon Ade",
    nameKo: "레몬 에이드",
    category: "beverage",
    image: "/images/menu/lemon-ade.jpg",
  },
  {
    id: "lemon-yuzu-tea",
    name: "Lemon Yuzu Tea",
    nameKo: "레몬 유자 티",
    category: "beverage",
    image: "/images/menu/lemon-yuzu-tea.jpg",
  },
  {
    id: "royal-milk-tea",
    name: "Royal Milk Tea",
    nameKo: "로얄 밀크 티",
    category: "beverage",
    image: "/images/menu/royal-milk-tea.jpg",
  },
  {
    id: "real-chocolat",
    name: "Real Chocolat",
    nameKo: "리얼 쇼콜라",
    category: "beverage",
    image: "/images/menu/real-chocolat.jpg",
  },
  {
    id: "mango-latte",
    name: "Mango Latte",
    nameKo: "망고 라떼",
    category: "beverage",
    image: "/images/menu/mango-latte.jpg",
  },
  {
    id: "banana-bubble-tea",
    name: "Banana Bubble Tea",
    nameKo: "바나나 버블티",
    category: "beverage",
    image: "/images/menu/banana-bubble-tea.jpg",
  },
  {
    id: "white-peach-oolong",
    name: "White Peach Oolong",
    nameKo: "백도 우롱",
    category: "beverage",
    image: "/images/menu/white-peach-oolong.jpg",
  },
  {
    id: "berry-hibiscus",
    name: "Berry Hibiscus",
    nameKo: "베리 히비스커스",
    category: "beverage",
    image: "/images/menu/berry-hibiscus.jpg",
  },
  {
    id: "seolhyang-strawberry-latte",
    name: "Seolhyang Strawberry Latte",
    nameKo: "설향 딸기 라떼",
    category: "beverage",
    image: "/images/menu/seolhyang-strawberry-latte.jpg",
  },
  {
    id: "pure-milk",
    name: "Pure Milk",
    nameKo: "순수 우유",
    category: "beverage",
    image: "/images/menu/pure-milk.jpg",
  },
  {
    id: "apple-mango-iced-tea",
    name: "Apple Mango Iced Tea",
    nameKo: "애플망고 아이스 티",
    category: "beverage",
    image: "/images/menu/apple-mango-iced-tea.jpg",
  },
  {
    id: "yeongam-sweet-potato-latte",
    name: "Yeongam Sweet Potato Latte",
    nameKo: "영암 고구마 라떼",
    category: "beverage",
    image: "/images/menu/yeongam-sweet-potato-latte.jpg",
  },
  {
    id: "grapefruit-ade",
    name: "Grapefruit Ade",
    nameKo: "자몽 에이드",
    category: "beverage",
    image: "/images/menu/grapefruit-ade.jpg",
  },
  {
    id: "zero-peach-iced-tea",
    name: "Zero Peach Iced Tea",
    nameKo: "제로 복숭아 아이스티",
    category: "beverage",
    image: "/images/menu/zero-peach-iced-tea.jpg",
  },
  {
    id: "jeju-matcha-latte",
    name: "Jeju Matcha Latte",
    nameKo: "제주 말차 라떼",
    category: "beverage",
    image: "/images/menu/jeju-matcha-latte.jpg",
  },
  {
    id: "jeju-misutgaru",
    name: "Jeju Misutgaru",
    nameKo: "제주 미숫가루",
    category: "beverage",
    image: "/images/menu/jeju-misutgaru.jpg",
  },
  {
    id: "jeju-matcha-bubble-tea",
    name: "Jeju Matcha Bubble Tea",
    nameKo: "제주 말차 버블티",
    category: "beverage",
    image: "/images/menu/jeju-matcha-bubble-tea.jpg",
  },
  {
    id: "ginger-pear-tea",
    name: "Ginger Pear Tea",
    nameKo: "진저 배 티",
    category: "beverage",
    image: "/images/menu/ginger-pear-tea.jpg",
  },
  {
    id: "green-grape-ade",
    name: "Green Grape Ade",
    nameKo: "청포도 에이드",
    category: "beverage",
    image: "/images/menu/green-grape-ade.jpg",
  },
  {
    id: "peach-boy",
    name: "Peach Boy",
    nameKo: "피치보이",
    category: "beverage",
    image: "/images/menu/peach-boy.jpg",
  },
  {
    id: "honey-chamomile",
    name: "Honey Chamomile",
    nameKo: "허니 캐모마일",
    category: "beverage",
    image: "/images/menu/honey-chamomile.jpg",
  },
  {
    id: "black-sugar-bubble-ice-cream-ic",
    name: "Black Sugar Bubble Ice Cream Ic",
    nameKo: "흑당 버블 아이스크림",
    category: "beverage",
    image: "/images/menu/black-sugar-bubble-ice-cream-ic.jpg",
  },
  // Blended
  {
    id: "honey-pear-smoothie",
    name: "Honey Pear Smoothie",
    nameKo: "꿀배 스무디",
    category: "blended",
    image: "/images/menu/honey-pear-smoothie.jpg",
  },
  {
    id: "strawberry-banana-juice",
    name: "Strawberry Banana Juice",
    nameKo: "딸기 바나나 주스",
    category: "blended",
    image: "/images/menu/strawberry-banana-juice.jpg",
  },
  {
    id: "strawberry-shake",
    name: "Strawberry Shake",
    nameKo: "딸기 쉐이크",
    category: "blended",
    image: "/images/menu/strawberry-shake.jpg",
  },
  {
    id: "strawberry-yogurt-smoothie",
    name: "Strawberry Yogurt Smoothie",
    nameKo: "딸기 요거트 스무디",
    category: "blended",
    image: "/images/menu/strawberry-yogurt-smoothie.jpg",
  },
  {
    id: "strawberry-yuzu-smoothie",
    name: "Strawberry Yuzu Smoothie",
    nameKo: "딸기 유자 스무디",
    category: "blended",
    image: "/images/menu/strawberry-yuzu-smoothie.jpg",
  },
  {
    id: "rice-shake",
    name: "Rice Shake",
    nameKo: "라이스 쉐이크",
    category: "blended",
    image: "/images/menu/rice-shake.jpg",
  },
  {
    id: "red-grapefruit-smoothie",
    name: "Red Grapefruit Smoothie",
    nameKo: "레드자몽 스무디",
    category: "blended",
    image: "/images/menu/red-grapefruit-smoothie.jpg",
  },
  {
    id: "real-watermelon-juice",
    name: "Real Watermelon Juice",
    nameKo: "리얼 수박 수즈",
    category: "blended",
    image: "/images/menu/real-watermelon-juice.jpg",
  },
  {
    id: "mango-banana-smoothie",
    name: "Mango Banana Smoothie",
    nameKo: "망고 바나나 스무디",
    category: "blended",
    image: "/images/menu/mango-banana-smoothie.jpg",
  },
  {
    id: "mango-yogurt-smoothie",
    name: "Mango Yogurt Smoothie",
    nameKo: "망고 요거트 스무디",
    category: "blended",
    image: "/images/menu/mango-yogurt-smoothie.jpg",
  },
  {
    id: "mint-choco-frappe",
    name: "Mint Choco Frappe",
    nameKo: "민트 초코 프라페",
    category: "blended",
    image: "/images/menu/mint-choco-frappe.jpg",
  },
  {
    id: "milk-shake",
    name: "Milk Shake",
    nameKo: "밀크쉐이크",
    category: "blended",
    image: "/images/menu/milk-shake.jpg",
  },
  {
    id: "blueberry-yogurt-smoothie",
    name: "Blueberry Yogurt Smoothie",
    nameKo: "블루베리 요거트 스무디",
    category: "blended",
    image: "/images/menu/blueberry-yogurt-smoothie.jpg",
  },
  {
    id: "jeju-matcha-frappe",
    name: "Jeju Matcha Frappe",
    nameKo: "제주 말차 프라페",
    category: "blended",
    image: "/images/menu/jeju-matcha-frappe.jpg",
  },
  {
    id: "jeju-lemon-smoothie",
    name: "Jeju Lemon Smoothie",
    nameKo: "제주 레몬 스무디",
    category: "blended",
    image: "/images/menu/jeju-lemon-smoothie.jpg",
  },
  {
    id: "green-grape-smoothie",
    name: "Green Grape Smoothie",
    nameKo: "청포도 스무디",
    category: "blended",
    image: "/images/menu/green-grape-smoothie.jpg",
  },
  {
    id: "choco-banana-smoothie",
    name: "Choco Banana Smoothie",
    nameKo: "초코 바나나 스무디",
    category: "blended",
    image: "/images/menu/choco-banana-smoothie.jpg",
  },
  {
    id: "choco-shake",
    name: "Choco Shake",
    nameKo: "초코 쉐이크",
    category: "blended",
    image: "/images/menu/choco-shake.jpg",
  },
  {
    id: "coffee-shake",
    name: "Coffee Shake",
    nameKo: "커피 쉐이크",
    category: "blended",
    image: "/images/menu/coffee-shake.jpg",
  },
  {
    id: "cup-bingsu",
    name: "Cup Bingsu",
    nameKo: "컵빙수",
    category: "blended",
    image: "/images/menu/cup-bingsu.jpg",
  },
  {
    id: "plain-yogurt-smoothie",
    name: "Plain Yogurt Smoothie",
    nameKo: "플레인 요거트 스무디",
    category: "blended",
    image: "/images/menu/plain-yogurt-smoothie.jpg",
  },
  {
    id: "hadong-plum-smoothie",
    name: "Hadong Plum Smoothie",
    nameKo: "하동 매실 스무디",
    category: "blended",
    image: "/images/menu/hadong-plum-smoothie.jpg",
  },
  // Bottle
  {
    id: "bottle-honey-grapefruit-tea",
    name: "Bottle Honey Grapefruit Tea",
    nameKo: "보틀 꿀 자몽 티",
    category: "bottle",
    image: "/images/menu/bottle-honey-grapefruit-tea.jpg",
  },
  {
    id: "bottle-double-choco-latte",
    name: "Bottle Double Choco Latte",
    nameKo: "보틀 더블 초코 라떼",
    category: "bottle",
    image: "/images/menu/bottle-double-choco-latte.jpg",
  },
  {
    id: "bottle-dolce-latte",
    name: "Bottle Dolce Latte",
    nameKo: "보틀 돌체 라떼",
    category: "bottle",
    image: "/images/menu/bottle-dolce-latte.jpg",
  },
  {
    id: "bottle-strawberry-iced-tea",
    name: "Bottle Strawberry Iced Tea",
    nameKo: "보틀 딸기 아이스 티",
    category: "bottle",
    image: "/images/menu/bottle-strawberry-iced-tea.jpg",
  },
  {
    id: "bottle-lemon-earl-grey-tea",
    name: "Bottle Lemon Earl Grey Tea",
    nameKo: "보틀 레몬 얼그레이 티",
    category: "bottle",
    image: "/images/menu/bottle-lemon-earl-grey-tea.jpg",
  },
  {
    id: "bottle-lemon-ade",
    name: "Bottle Lemon Ade",
    nameKo: "보틀 레몬 에이드",
    category: "bottle",
    image: "/images/menu/bottle-lemon-ade.jpg",
  },
  {
    id: "bottle-lemon-yuzu-tea",
    name: "Bottle Lemon Yuzu Tea",
    nameKo: "보틀 레몬 유자 티",
    category: "bottle",
    image: "/images/menu/bottle-lemon-yuzu-tea.jpg",
  },
  {
    id: "bottle-royal-milk-tea",
    name: "Bottle Royal Milk Tea",
    nameKo: "보틀 로얄 밀크 티",
    category: "bottle",
    image: "/images/menu/bottle-royal-milk-tea.jpg",
  },
  {
    id: "bottle-mango-latte",
    name: "Bottle Mango Latte",
    nameKo: "보틀 망고 라떼",
    category: "bottle",
    image: "/images/menu/bottle-mango-latte.jpg",
  },
  {
    id: "bottle-banana-oat-latte",
    name: "Bottle Banana Oat Latte",
    nameKo: "보틀 바나나 오트 라떼",
    category: "bottle",
    image: "/images/menu/bottle-banana-oat-latte.jpg",
  },
  {
    id: "bottle-vanilla-bean-latte",
    name: "Bottle Vanilla Bean Latte",
    nameKo: "보틀 바닐라 빈 라떼",
    category: "bottle",
    image: "/images/menu/bottle-vanilla-bean-latte.jpg",
  },
  {
    id: "bottle-valrhona-chocolate",
    name: "Bottle Valrhona Chocolate",
    nameKo: "보틀 발로나 초콜릿",
    category: "bottle",
    image: "/images/menu/bottle-valrhona-chocolate.jpg",
  },
  {
    id: "bottle-berry-hibiscus",
    name: "Bottle Berry Hibiscus",
    nameKo: "보틀 베리 히비스커스",
    category: "bottle",
    image: "/images/menu/bottle-berry-hibiscus.jpg",
  },
  {
    id: "bottle-barley-misutgaru",
    name: "Bottle Barley Misutgaru",
    nameKo: "보틀 보리 미숫가루",
    category: "bottle",
    image: "/images/menu/bottle-barley-misutgaru.jpg",
  },
  {
    id: "bottle-seolhyang-strawberry-latte",
    name: "Bottle Seolhyang Strawberry Latte",
    nameKo: "보틀 설향 딸기 라떼",
    category: "bottle",
    image: "/images/menu/bottle-seolhyang-strawberry-latte.jpg",
  },
  {
    id: "bottle-pure-milk",
    name: "Bottle Pure Milk",
    nameKo: "보틀 순수 우유",
    category: "bottle",
    image: "/images/menu/bottle-pure-milk.jpg",
  },
  {
    id: "bottle-cinnamon-cafe-latte",
    name: "Bottle Cinnamon Cafe Latte",
    nameKo: "보틀 시나몬 카페 라떼",
    category: "bottle",
    image: "/images/menu/bottle-cinnamon-cafe-latte.jpg",
  },
  {
    id: "bottle-americano",
    name: "Bottle Americano",
    nameKo: "보틀 아메리카노",
    category: "bottle",
    image: "/images/menu/bottle-americano.jpg",
  },
  {
    id: "bottle-ah-shot-chu",
    name: "Bottle Ah Shot Chu",
    nameKo: "보틀 아샷추",
    category: "bottle",
    image: "/images/menu/bottle-ah-shot-chu.jpg",
  },
  {
    id: "bottle-apple-mango-iced-tea",
    name: "Bottle Apple Mango Iced Tea",
    nameKo: "보틀 애플망고 아이스 티",
    category: "bottle",
    image: "/images/menu/bottle-apple-mango-iced-tea.jpg",
  },
  {
    id: "bottle-earl-grey-vanilla-tea-latte",
    name: "Bottle Earl Grey Vanilla Tea Latte",
    nameKo: "보틀 얼그레이 바닐라 티 라떼",
    category: "bottle",
    image: "/images/menu/bottle-earl-grey-vanilla-tea-latte.jpg",
  },
  {
    id: "bottle-sweet-potato-latte",
    name: "Bottle Sweet Potato Latte",
    nameKo: "보틀 영암 고구마 라떼",
    category: "bottle",
    image: "/images/menu/bottle-sweet-potato-latte.jpg",
  },
  {
    id: "bottle-grapefruit-ade",
    name: "Bottle Grapefruit Ade",
    nameKo: "보틀 자몽 에이드",
    category: "bottle",
    image: "/images/menu/bottle-grapefruit-ade.jpg",
  },
  {
    id: "bottle-jeju-matcha-latte",
    name: "Bottle Jeju Matcha Latte",
    nameKo: "보틀 제주 말차 라떼",
    category: "bottle",
    image: "/images/menu/bottle-jeju-matcha-latte.jpg",
  },
  {
    id: "bottle-jeju-matcha-cafe-latte",
    name: "Bottle Jeju Matcha Cafe Latte",
    nameKo: "보틀 제주 말차 카페 라떼",
    category: "bottle",
    image: "/images/menu/bottle-jeju-matcha-cafe-latte.jpg",
  },
  {
    id: "bottle-jeju-hojicha",
    name: "Bottle Jeju Hojicha",
    nameKo: "보틀 제주 호지차",
    category: "bottle",
    image: "/images/menu/bottle-jeju-hojicha.jpg",
  },
  {
    id: "bottle-ginger-pear-tea",
    name: "Bottle Ginger Pear Tea",
    nameKo: "보틀 진저 배 티",
    category: "bottle",
    image: "/images/menu/bottle-ginger-pear-tea.jpg",
  },
  {
    id: "bottle-green-grape-ade",
    name: "Bottle Green Grape Ade",
    nameKo: "보틀 청포도 에이드",
    category: "bottle",
    image: "/images/menu/bottle-green-grape-ade.jpg",
  },
  {
    id: "bottle-caramel-macchiato",
    name: "Bottle Caramel Macchiato",
    nameKo: "보틀 카라멜 마끼야또",
    category: "bottle",
    image: "/images/menu/bottle-caramel-macchiato.jpg",
  },
  {
    id: "bottle-cafe-latte",
    name: "Bottle Cafe Latte",
    nameKo: "보틀 카페 라떼",
    category: "bottle",
    image: "/images/menu/bottle-cafe-latte.jpg",
  },
  {
    id: "bottle-cafe-mocha",
    name: "Bottle Cafe Mocha",
    nameKo: "보틀 카페 모카",
    category: "bottle",
    image: "/images/menu/bottle-cafe-mocha.jpg",
  },
  {
    id: "bottle-cold-brew-dolce-latte",
    name: "Bottle Cold Brew Dolce Latte",
    nameKo: "보틀 콜드 브루 돌체 라떼",
    category: "bottle",
    image: "/images/menu/bottle-cold-brew-dolce-latte.jpg",
  },
  {
    id: "bottle-cold-brew-americano",
    name: "Bottle Cold Brew Americano",
    nameKo: "보틀 콜드 브루 아메리카노",
    category: "bottle",
    image: "/images/menu/bottle-cold-brew-americano.jpg",
  },
  {
    id: "bottle-cold-brew-cafe-latte",
    name: "Bottle Cold Brew Cafe Latte",
    nameKo: "보틀 콜드 브루 카페 라떼",
    category: "bottle",
    image: "/images/menu/bottle-cold-brew-cafe-latte.jpg",
  },
  {
    id: "bottle-toffee-nut-latte",
    name: "Bottle Toffee Nut Latte",
    nameKo: "보틀 토피넛 라떼",
    category: "bottle",
    image: "/images/menu/bottle-toffee-nut-latte.jpg",
  },
  {
    id: "bottle-peppermint",
    name: "Bottle Peppermint",
    nameKo: "보틀 페퍼민트",
    category: "bottle",
    image: "/images/menu/bottle-peppermint.jpg",
  },
  {
    id: "bottle-honey-chamomile",
    name: "Bottle Honey Chamomile",
    nameKo: "보틀 허니 캐모마일",
    category: "bottle",
    image: "/images/menu/bottle-honey-chamomile.jpg",
  },
  {
    id: "bottle-white-americano",
    name: "Bottle White Americano",
    nameKo: "보틀 화이트 아메리카노",
    category: "bottle",
    image: "/images/menu/bottle-white-americano.jpg",
  },
  // Bakery
  {
    id: "canele",
    name: "Canele",
    nameKo: "까눌레",
    category: "bakery",
    image: "/images/menu/canele.jpg",
  },
  {
    id: "dubai-choco-financier",
    name: "Dubai Choco Financier",
    nameKo: "두바이 초코 휘낭시에",
    category: "bakery",
    image: "/images/menu/dubai-choco-financier.jpg",
  },
  {
    id: "strawberry-donut",
    name: "Strawberry Donut",
    nameKo: "딸기 도넛",
    category: "bakery",
    image: "/images/menu/strawberry-donut.jpg",
  },
  {
    id: "lemon-donut",
    name: "Lemon Donut",
    nameKo: "레몬 도넛",
    category: "bakery",
    image: "/images/menu/lemon-donut.jpg",
  },
  {
    id: "lemon-cake",
    name: "Lemon Cake",
    nameKo: "레몬케이크",
    category: "bakery",
    image: "/images/menu/lemon-cake.jpg",
  },
  {
    id: "roasted-macadamia-financier",
    name: "Roasted Macadamia Financier",
    nameKo: "로스티드 마카다미아 휘낭시에",
    category: "bakery",
    image: "/images/menu/roasted-macadamia-financier.jpg",
  },
  {
    id: "fig-cream-cheese-baton-financier",
    name: "Fig Cream Cheese Baton Financier",
    nameKo: "무화과크림치즈 바통휘낭시에",
    category: "bakery",
    image: "/images/menu/fig-cream-cheese-baton-financier.jpg",
  },
  {
    id: "milk-scone",
    name: "Milk Scone",
    nameKo: "밀크 스콘",
    category: "bakery",
    image: "/images/menu/milk-scone.jpg",
  },
  {
    id: "vanilla-donut",
    name: "Vanilla Donut",
    nameKo: "바닐라 도넛",
    category: "bakery",
    image: "/images/menu/vanilla-donut.jpg",
  },
  {
    id: "valrhona-smore-cookie",
    name: "Valrhona Smore Cookie",
    nameKo: "발로나 스모어 쿠키",
    category: "bakery",
    image: "/images/menu/valrhona-smore-cookie.jpg",
  },
  {
    id: "bacon-egg-mayo-bread",
    name: "Bacon Egg Mayo Bread",
    nameKo: "베이컨 에그마요 빵",
    category: "bakery",
    image: "/images/menu/bacon-egg-mayo-bread.jpg",
  },
  {
    id: "ssuk-red-bean-smore-cookie",
    name: "Ssuk Red Bean Smore Cookie",
    nameKo: "쑥단팥 스모어쿠키",
    category: "bakery",
    image: "/images/menu/ssuk-red-bean-smore-cookie.jpg",
  },
  {
    id: "almond-biscotti",
    name: "Almond Biscotti",
    nameKo: "아몬드 비스코티",
    category: "bakery",
    image: "/images/menu/almond-biscotti.jpg",
  },
  {
    id: "yakgwa-baton-financier",
    name: "Yakgwa Baton Financier",
    nameKo: "약과 바통휘낭시에",
    category: "bakery",
    image: "/images/menu/yakgwa-baton-financier.jpg",
  },
  {
    id: "earl-grey-baton-financier",
    name: "Earl Grey Baton Financier",
    nameKo: "얼그레이 바통휘낭시에",
    category: "bakery",
    image: "/images/menu/earl-grey-baton-financier.jpg",
  },
  {
    id: "milk-donut",
    name: "Milk Donut",
    nameKo: "우유 도넛",
    category: "bakery",
    image: "/images/menu/milk-donut.jpg",
  },
  {
    id: "walnut-choco-cookie",
    name: "Walnut Choco Cookie",
    nameKo: "월넛 초코 쿠키",
    category: "bakery",
    image: "/images/menu/walnut-choco-cookie.jpg",
  },
  {
    id: "choco-donut",
    name: "Choco Donut",
    nameKo: "초코 도넛",
    category: "bakery",
    image: "/images/menu/choco-donut.jpg",
  },
  {
    id: "chocochip-biscotti",
    name: "Chocochip Biscotti",
    nameKo: "초코칩 비스코티",
    category: "bakery",
    image: "/images/menu/chocochip-biscotti.jpg",
  },
  {
    id: "churros-baton-financier",
    name: "Churros Baton Financier",
    nameKo: "츄러스 바통휘낭시에",
    category: "bakery",
    image: "/images/menu/churros-baton-financier.jpg",
  },
  {
    id: "cookies-cream-donut",
    name: "Cookies Cream Donut",
    nameKo: "쿠키앤 크림 도넛",
    category: "bakery",
    image: "/images/menu/cookies-cream-donut.jpg",
  },
  {
    id: "famille-kahlua-macchiato",
    name: "Famille Kahlua Macchiato",
    nameKo: "깔루아 마키아토",
    category: "bakery",
    image: "/images/menu/famille-kahlua-macchiato.jpg",
  },
  {
    id: "famille-ny-cheesecake",
    name: "Famille Ny Cheesecake",
    nameKo: "뉴욕 치즈케이크",
    category: "bakery",
    image: "/images/menu/famille-ny-cheesecake.jpg",
  },
  {
    id: "famille-strawberry-granola-cookie",
    name: "Famille Strawberry Granola Cookie",
    nameKo: "딸기 그래놀라 쫀득쿠키",
    category: "bakery",
    image: "/images/menu/famille-strawberry-granola-cookie.jpg",
  },
  {
    id: "famille-strawberry-macaron",
    name: "Famille Strawberry Macaron",
    nameKo: "딸기 마카롱",
    category: "bakery",
    image: "/images/menu/famille-strawberry-macaron.jpg",
  },
  {
    id: "famille-strawberry-cookies-cream-cookie",
    name: "Famille Strawberry Cookies Cream Cookie",
    nameKo: "딸기 쿠키앤크림 쫀득쿠키",
    category: "bakery",
    image: "/images/menu/famille-strawberry-cookies-cream-cookie.jpg",
  },
  {
    id: "famille-milk-crepe",
    name: "Famille Milk Crepe",
    nameKo: "밀크 크레이프",
    category: "bakery",
    image: "/images/menu/famille-milk-crepe.jpg",
  },
  {
    id: "famille-bulgogi-ciabatta",
    name: "Famille Bulgogi Ciabatta",
    nameKo: "불고기 치아바타",
    category: "bakery",
    image: "/images/menu/famille-bulgogi-ciabatta.jpg",
  },
  {
    id: "famille-black-forest-cream",
    name: "Famille Black Forest Cream",
    nameKo: "블랙 포레스트 생크림",
    category: "bakery",
    image: "/images/menu/famille-black-forest-cream.jpg",
  },
  {
    id: "famille-cream-castella",
    name: "Famille Cream Castella",
    nameKo: "생크림 카스테라",
    category: "bakery",
    image: "/images/menu/famille-cream-castella.jpg",
  },
  {
    id: "famille-devils-choco-cake",
    name: "Famille Devils Choco Cake",
    nameKo: "악마의 초코 케익",
    category: "bakery",
    image: "/images/menu/famille-devils-choco-cake.jpg",
  },
  {
    id: "famille-onion-bagel",
    name: "Famille Onion Bagel",
    nameKo: "어니언 베이글",
    category: "bakery",
    image: "/images/menu/famille-onion-bagel.jpg",
  },
  {
    id: "famille-condensed-milk-morning",
    name: "Famille Condensed Milk Morning",
    nameKo: "연유 밀크 모닝",
    category: "bakery",
    image: "/images/menu/famille-condensed-milk-morning.jpg",
  },
  {
    id: "famille-original-bun",
    name: "Famille Original Bun",
    nameKo: "오리지날번",
    category: "bakery",
    image: "/images/menu/famille-original-bun.jpg",
  },
  {
    id: "famille-injeolmi-macaron",
    name: "Famille Injeolmi Macaron",
    nameKo: "인절미 마카롱",
    category: "bakery",
    image: "/images/menu/famille-injeolmi-macaron.jpg",
  },
  {
    id: "famille-english-muffin-sandwich",
    name: "Famille English Muffin Sandwich",
    nameKo: "잉글리쉬 머핀 샌드위치",
    category: "bakery",
    image: "/images/menu/famille-english-muffin-sandwich.jpg",
  },
  {
    id: "famille-choco-macaron",
    name: "Famille Choco Macaron",
    nameKo: "초코 마카롱",
    category: "bakery",
    image: "/images/menu/famille-choco-macaron.jpg",
  },
  {
    id: "famille-cheese-bagel",
    name: "Famille Cheese Bagel",
    nameKo: "치즈 베이글",
    category: "bakery",
    image: "/images/menu/famille-cheese-bagel.jpg",
  },
  {
    id: "famille-croque-monsieur",
    name: "Famille Croque Monsieur",
    nameKo: "크로크무슈",
    category: "bakery",
    image: "/images/menu/famille-croque-monsieur.jpg",
  },
  {
    id: "famille-cream-red-bean-bread",
    name: "Famille Cream Red Bean Bread",
    nameKo: "크림 단팥빵",
    category: "bakery",
    image: "/images/menu/famille-cream-red-bean-bread.jpg",
  },
  {
    id: "famille-creme-brulee-macaron",
    name: "Famille Creme Brulee Macaron",
    nameKo: "크림브륄레 마카롱",
    category: "bakery",
    image: "/images/menu/famille-creme-brulee-macaron.jpg",
  },
  {
    id: "famille-tiramisu",
    name: "Famille Tiramisu",
    nameKo: "티라미수",
    category: "bakery",
    image: "/images/menu/famille-tiramisu.jpg",
  },
  {
    id: "famille-plain-bagel",
    name: "Famille Plain Bagel",
    nameKo: "플레인 베이글",
    category: "bakery",
    image: "/images/menu/famille-plain-bagel.jpg",
  },
  {
    id: "famille-ham-cheese-taiwan-sandwich",
    name: "Famille Ham Cheese Taiwan Sandwich",
    nameKo: "햄치즈 대만 샌드위치",
    category: "bakery",
    image: "/images/menu/famille-ham-cheese-taiwan-sandwich.jpg",
  },
  {
    id: "pearl-salt-financier",
    name: "Pearl Salt Financier",
    nameKo: "펄솔트 휘낭시에",
    category: "bakery",
    image: "/images/menu/pearl-salt-financier.jpg",
  },
  {
    id: "honey-crispy-financier",
    name: "Honey Crispy Financier",
    nameKo: "허니 크리스피 휘낭시에",
    category: "bakery",
    image: "/images/menu/honey-crispy-financier.jpg",
  },
  // Ice-cream
  {
    id: "strawberry-ice-cream",
    name: "Strawberry Ice Cream",
    nameKo: "딸기 아이스크림",
    category: "ice-cream",
    image: "/images/menu/strawberry-ice-cream.jpg",
  },
  {
    id: "strawberry-cookie-ice-cream-frappe",
    name: "Strawberry Cookie Ice Cream Frappe",
    nameKo: "딸기 쿠키 아이스크림 프라페",
    category: "ice-cream",
    image: "/images/menu/strawberry-cookie-ice-cream-frappe.jpg",
  },
  {
    id: "matcha-ice-cream",
    name: "Matcha Ice Cream",
    nameKo: "말차 아이스크림",
    category: "ice-cream",
    image: "/images/menu/matcha-ice-cream.jpg",
  },
  {
    id: "matcha-cookie-ice-cream-frappe",
    name: "Matcha Cookie Ice Cream Frappe",
    nameKo: "말차 쿠키 아이스크림 프라페",
    category: "ice-cream",
    image: "/images/menu/matcha-cookie-ice-cream-frappe.jpg",
  },
  {
    id: "black-cookie-ice-cream",
    name: "Black Cookie Ice Cream",
    nameKo: "블랙쿠키 아이스크림",
    category: "ice-cream",
    image: "/images/menu/black-cookie-ice-cream.jpg",
  },
  {
    id: "soft-ice-cream",
    name: "Soft Ice Cream",
    nameKo: "소프트 아이스크림",
    category: "ice-cream",
    image: "/images/menu/soft-ice-cream.jpg",
  },
  {
    id: "ice-cream-latte",
    name: "Ice Cream Latte",
    nameKo: "아이스크림 라떼",
    category: "ice-cream",
    image: "/images/menu/ice-cream-latte.jpg",
  },
  {
    id: "apple-mango-ice-cream",
    name: "Apple Mango Ice Cream",
    nameKo: "애플망고 아이스크림",
    category: "ice-cream",
    image: "/images/menu/apple-mango-ice-cream.jpg",
  },
  {
    id: "espresso-ice-cream",
    name: "Espresso Ice Cream",
    nameKo: "에스프레소 아이스크림",
    category: "ice-cream",
    image: "/images/menu/espresso-ice-cream.jpg",
  },
  {
    id: "injeolmi-ice-cream",
    name: "Injeolmi Ice Cream",
    nameKo: "인절미 아이스크림",
    category: "ice-cream",
    image: "/images/menu/injeolmi-ice-cream.jpg",
  },
  {
    id: "choco-ice-cream",
    name: "Choco Ice Cream",
    nameKo: "초코 아이스크림",
    category: "ice-cream",
    image: "/images/menu/choco-ice-cream.jpg",
  },
  {
    id: "black-sugar-bubble-ice-cream-ic",
    name: "Black Sugar Bubble Ice Cream Ic",
    nameKo: "흑당 버블 아이스크림",
    category: "ice-cream",
    image: "/images/menu/black-sugar-bubble-ice-cream-ic.jpg",
  },
];
